### ISSUE TITLE
place_buy_order method doesn't handle steam error codes

### ISSUE THREAD

**Issue by yesworId** [somespecialone/aiosteampy#65]
### Initial Checks

- [X] I have searched the existing issues for a duplicate and I'm sure this is something new
- [X] I am confident that the issue in the project code

### Description

I was testing this library, after initial login tests I couldn't log into my account. 
Default login function wasn't working for me. This was error I got:
![image](https://github.com/user-attachments/assets/1e938290-80a8-4fea-aaec-9ddc9e3f4526)

### Steps To Reproduce

I was using the default login function from this library. Only after I changed code to this one, I logged successfully:
```python
    async def login(self: "SteamCommunityMixin", *, init_data=True, init_session=True):
        """
        Perform login.
        Populate `api_key`, `trade_token`, `wallet_country`, `wallet_currency` fields if it is required.

        :param init_data: fetch initial required data (api key, trade token, wallet_currency/wallet_country)
        :param init_session: init session before start auth process.
            Set this to False if you already make requests to steam from current client.
        :raises ApiError: when failed to obtain rsa key, update steam guard code
        :raises LoginError: other login process errors
        """

        # https://github.com/bukson/steampy/blob/fe0433c8cf7020318cfbbc22e79028a7576374ee/steampy/login.py#L67
        # https://github.com/DoctorMcKay/node-steam-session/blob/698469cdbad3e555dda10c81f580f1ee3960156f/examples/login-to-web-with-2fa.ts#L13
        init_session and await self.session.get(STEAM_URL.COMMUNITY)

        session_data = await self._begin_auth_session_with_credentials()
        await self._update_auth_session_with_steam_guard_code(session_data)
        await self._poll_auth_session_status(session_data)
        fin_data = await self._finalize_login()  # there can be retrieved steam id

        # https://github.com/DoctorMcKay/node-steam-session/blob/64463d7468c1c860afb80164b8c5831e629f657f/src/LoginSession.ts#L845
        transfers = [asyncio.create_task(self._perform_transfer(d, fin_data["steamID"])) for d in
                     fin_data["transfer_info"]]
        done, _ = await asyncio.wait(transfers, return_when=asyncio.FIRST_COMPLETED)

        # Transfers exception check ?

        self._set_web_cookies(done.pop().result())

        init_data and await self._init_data()

        self._is_logged = True

```

The only change is
```python
        transfers = [asyncio.create_task(self._perform_transfer(d, fin_data["steamID"])) for d in
                     fin_data["transfer_info"]]
```

But I don't really know is it good or not

### Environment

```Text
Windows
Python
```

**Comment by somespecialone** [comment]
Good day time! You make it right. Since python version 3.11 `asyncio.wait` accepts only tasks and not coroutines. But, I already fix it in lib version `0.5.2`, so you just need to update

**Comment by yesworId** [comment]
> Good day time! You make it right. Since python version 3.11 `asyncio.wait` accepts only tasks and not coroutines. But, I already fix it in lib version `0.5.2`, so you just need to update

Oh yeah, my bad.

**Comment by yesworId** [comment]
I've had an issue with [*place_buy_order*](https://github.com/somespecialone/aiosteampy/blob/master/aiosteampy/market.py#L163) function

Here's my fix.
```python
    async def place_buy_order(
        self: "SteamCommunityMixin",
        obj: str | ItemDescription,
        app_id: int = None,
        *,
        price: int,
        quantity=1,
        **kwargs: T_KWARGS,
    ) -> int:
        """
        Place buy order on market.

        :param obj: `ItemDescription` or market hash name
        :param app_id: app id if `obj` is market hash name
        :param price: price of single item
        :param quantity: just quantity
        :return: buy order id
        :raises ApiError:
        """

        if isinstance(obj, ItemDescription):
            name = obj.market_hash_name
            app_id = obj.game[0]
        else:
            name = obj

        data = {
            "sessionid": self.session_id,
            "currency": self._wallet_currency.value,
            "appid": app_id,
            "market_hash_name": name,
            "price_total": price * quantity,
            "quantity": quantity,
            **kwargs,
        }
        headers = {"Referer": str(STEAM_URL.MARKET / f"listings/{app_id}/{name}")}
        r = await self.session.post(STEAM_URL.MARKET / "createbuyorder/", data=data, headers=headers)
        rj: dict = await r.json()
        if (success := rj.get("success")) != 1:
            raise ApiError(message := rj.get("message"))

        return rj
```
I would have change this:
```python
        rj: dict = await r.json()
        if not rj.get("success"):
            raise ApiError("Failed to create buy order.", rj)

        return int(rj["buy_orderid"])
```
to this:
```python
        rj: dict = await r.json()
        if (success := rj.get("success")) != 1:
            raise ApiError(message := rj.get("message"))

        return rj
```
In my opinion it's better. If Steam API error occurs then base function is gonna get KeyError Exception, only because response doesn't have "buy_order_id" key. Also because of this user will know exact error status and won't looking for it's code status on https://steamerrors.com/

For example in case of success = 29, exception will raise:
![image](https://github.com/user-attachments/assets/c12dc6ab-657f-4bcd-83f2-9c99e7119abe)

But also, maybe we should raise message and success number, in case if user need to handle different situations. What's your thoughts?

**Comment by somespecialone** [comment]
Do we always receive data with `message` field if `success` is not 1 (false)? If this is guaranteed, than we can depend on steam `message` and raise an error with that message provided. If it is not, we can keep raise logic unchanged, gives full view of data to user.

**Comment by yesworId** [comment]
I've tested it with different success codes and message was different every time. Success = 1 result only returns "success" and "buy_order_id" keys. These messages can be a good explanation of error that happened. But they are too long. I think better to raise ApiError Exception with its success code and maybe message.

**Comment by somespecialone** [comment]
I see. However, I think that best solution is to pass steam message and steam error code to some exception for more clarity. Aaand, that requires refactor. New error, like `SteamApiError` or old one `ApiError` with fields `message`, `error_code` and `data`
 for case when `success` is not present in data (malformed data, something else, we both know how Steam works). Such exception must be responsible for steam error codes in responses.
Ex.:
```python
class ApiError(Exception):
    def __init__(self, msg: str, error_code: int | None=None, data=None):
        self.msg = msg
        self.error_code = error_code
        self.data = data
```

In method:
```python
        ...
        success = rj.get("success")
        if success is None:  # malformed
            raise ApiError("Failed to create buy order: malformed response from Steam", data=rj)
        elif success != 1:
            raise ApiError(rj["message"], success)

        return int(rj["buy_orderid"])
```
Also, it would be good if we change and fix all methods where `ApiError` can be raised, and response data checked for `success`.

**Comment by somespecialone** [comment]
v0.6.0 handle `EResult` errors
